"""Build dist/FrameCast_PC_Setup.zip — the standalone PC-side download.

    python tools/build_pc_zip.py

The layout the user sees after extracting is deliberately flat at the top:

    FrameCast_PC_Setup/
        Install_FrameCast.vbs     <- the only thing they double-click
        README.txt
        FrameCast.ico             <- also what the Startup shortcut points at
        FrameCast.png
        pc_receiver/...
        reward_engine/...

reward_engine/ ships even though no service imports it, because demo_sender.py
does (`from reward_engine.reward_manager import ...`) and demo_sender is the
only way to check the virtual camera works without a phone in hand. Leaving it
out would put a module in the zip that cannot be run from the zip.

Contents are intentionally *not* the whole repo: no tests, no .venv, no logs,
no caches, nothing generated by a previous install.
"""

from __future__ import annotations

import argparse
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = REPO_ROOT / "dist"
ZIP_NAME = "FrameCast_PC_Setup.zip"
# Everything lands under this folder inside the zip, so extracting never
# scatters loose files into the user's Downloads folder.
TOP_LEVEL = "FrameCast_PC_Setup"

# Top-level files, copied as-is.
ROOT_FILES = [
    ("Install_FrameCast.vbs", "Install_FrameCast.vbs"),
    ("README.txt", "README.txt"),
    ("brand/framecast.ico", "FrameCast.ico"),
    ("brand/framecast_logo_256.png", "FrameCast.png"),
]

# Package directories. Only these suffixes ship, and only from the directory
# itself — subdirectories (tests/, __pycache__/, .venv/, logs/) never do.
PACKAGE_DIRS = ["pc_receiver", "reward_engine"]
PACKAGE_SUFFIXES = {".py", ".bat", ".vbs", ".txt"}

# Files that match the rules above but must not reach a user's PC anyway.
EXCLUDED_NAMES = {
    "setup_log.txt",         # written by a previous install on the build machine
    ".control_token",        # per-PC secret generated by control_server
    "requirements-dev.txt",  # pytest and the icon renderer; no user needs them
}


def collect() -> list[tuple[Path, str]]:
    """(source path, path inside the zip) for everything that ships."""
    entries: list[tuple[Path, str]] = []

    for source, target in ROOT_FILES:
        entries.append((REPO_ROOT / source, f"{TOP_LEVEL}/{target}"))

    for package in PACKAGE_DIRS:
        package_dir = REPO_ROOT / package
        for path in sorted(package_dir.iterdir()):
            if not path.is_file():
                continue
            if path.suffix not in PACKAGE_SUFFIXES or path.name in EXCLUDED_NAMES:
                continue
            entries.append((path, f"{TOP_LEVEL}/{package}/{path.name}"))

    return entries


def build(output: Path | None = None) -> Path:
    entries = collect()

    missing = [str(src.relative_to(REPO_ROOT)) for src, _ in entries if not src.exists()]
    if missing:
        raise SystemExit(
            "cannot build the zip, these are missing:\n  "
            + "\n  ".join(missing)
            + "\n\n(brand/* is generated — run: python tools/make_brand_assets.py)"
        )

    output = output or (DIST_DIR / ZIP_NAME)
    output.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        for source, arcname in entries:
            # A fixed timestamp keeps the zip byte-identical across rebuilds of
            # unchanged sources, so "did the download actually change?" is
            # answerable by hash. 1980-01-01 is the zip epoch.
            info = zipfile.ZipInfo(arcname, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, source.read_bytes())

    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help=f"where to write the zip (default: dist/{ZIP_NAME})",
    )
    args = parser.parse_args()

    output = build(args.output)
    with zipfile.ZipFile(output) as zf:
        names = zf.namelist()
    print(f"{output.relative_to(REPO_ROOT)}  ({output.stat().st_size:,} bytes, {len(names)} files)")
    for name in names:
        print(f"    {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
